export const types = {
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAIL: "LOGIN_FAIL",
	/* 	SET_FORM_ERRORS: "SET_FORM_ERRORS",
	SET_MESSAGE: "SET_MESSAGE", */
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAIL: "REGISTER_FAIL",
	LOGOUT: "LOGOUT",
	SUPERIN_FAIL: "SUPERIN_FAIL",
	SUPERIN_SUCCESS: "SUPERIN_SUCCESS",
	SUPEROUT: "SUPEROUT",
};
